# Generated by Django 4.0.6 on 2022-08-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_moive_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moive',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollars'), ('RUB', 'Rubles')], default='R', max_length=3),
        ),
    ]
