# Generated by Django 4.0.6 on 2022-08-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_moive_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Квентин Тарантино', max_length=100)),
                ('last_name', models.CharField(default='Квентин Тарантино', max_length=100)),
                ('director_emanil', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='moive',
            name='director',
        ),
    ]
