# Generated by Django 4.0.6 on 2022-08-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_director_remove_moive_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='moive',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movie_app.director'),
        ),
    ]
